### ISSUE TITLE
Reverse (natural) scrolling 

### ISSUE THREAD

**Issue by danielsz** [BlueDragonX/xf86-input-mtrack#113]
Reverse (natural) scrolling was working flawlessly until a recent kernel upgrade, where the settings below don't seem to achieve the desired effect. 

```
        Option "ScrollDownButton"       "4"
        Option "ScrollUpButton"         "5"
        Option "ScrollLeftButton"       "7"
        Option "ScrollRightButton"      "6"
```

Used with the bcm5974 driver and an Apple touchpad on a Macbook Air.

```
Linux daniel-MacBookAir 4.4.0-28-generic #47-Ubuntu SMP Fri Jun 24 10:09:13 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by ecly** [comment]
This works for me on a Macbook Pro 2014 with Arch Linux and most recent version of mtrack. 
https://aur.archlinux.org/packages/xf86-input-mtrack-git/
