### ISSUE TITLE
Mtrack freezes Ubuntu 16.04 on login screen

### ISSUE THREAD

**Issue by jborbik** [BlueDragonX/xf86-input-mtrack#124]
Removed

**Comment by Jendker** [comment]
It seems that the package xserver-xorg-input-mtrack is unmaintained what is causing the problem. Such tutorials are quite harmful... 

Could I only get the confirmation if it will work properly after manual buildon Ubuntu 16.04 with Kernel 4.10 on Mac?

Thank you!
