### ISSUE TITLE
mtrack config file is not found in ubuntu 4.15.0-32-generic

### ISSUE THREAD

**Issue by opheliagame** [BlueDragonX/xf86-input-mtrack#127]
I installed the driver using this git repository. Every works perfectly, the driver files are located in **/usr/lib/xorg/modules/input**. But I am unable to find any default config files in any of the usual directories.
**/usr/share/X11/xorg.conf.d/** doesn't have any, neither does **/etc/X11**. 

I was also able to find synaptics config files only in **/usr/share/X11/xorg.conf.d**, and nowhere else. So, I made a **10-mtrack.conf file**, and placed it in this directory, and logged out, but the X server couldn't start again due to a **parsing error** in a 10-quirks.conf file placed in the same directory. 

Even after renaming the above file to **40-mtrack.conf**, the parsing error persisted tho it shifted to another file. Only after removing the mtrack config file could the X server be started again. 

What am I missing?

**Comment by rynbrd** [comment]
There is no default config. The default config values are loaded by the driver. You must provide your own config file if you wish to override the defaults.

In all likelihood you have introduced a syntax error in your config file. You will need to figure that out. This doesn't really have anything to do with mtrack, though. Read the Xorg docs to learn about the appropriate syntax for Xorg config files.
