### ISSUE TITLE
Mouse sporadically moves when MBP lid closed and used in "docking" situation

### ISSUE THREAD

**Issue by zmingee** [BlueDragonX/xf86-input-mtrack#128]
First off, thanks for all the effort that's put into this project. It really increases the usability of the MBP trackpad.

I do have an issue however, that may seem strange. Sometimes, I like to use my laptop in a "docked" situation. I have the laptop plugged up to power, monitors, etc, and I close the lid. While I'm using it like this, though, there will be occasional movements of the mouse, or it won't move in a straight line as i move my BT mouse. After I open the lid, the issue goes away. I've never had the issue occur when the lid is open, only when closed.

Steps to reproduce, I'm not sure. I have a Mid-2014 MBP 15". When *I* close the lid, and use the laptop docked, the mouse will sporadically move. I don't know if it's limited to a MBP, or if it's the Retina screen, or.. I guess a possible solution would be a config option to allow disabling input when the lid is closed? Just spitballing.

Thanks for any help you can pass along.

**Comment by jcrben** [comment]
There's been no commits here since 2015. Seems that activity has shifted to https://github.com/p2rkw/xf86-input-mtrack

**Comment by zmingee** [comment]
@jcrben Thank you for the reminder about this bug report. I'll resubmit with the new upstream.
