### ISSUE TITLE
Build issue, automake "must install xorg-macros 1.8 or later before running autoconf/autogen"

### ISSUE THREAD

**Issue by jtpereyda** [BlueDragonX/xf86-input-mtrack#27]
Not sure if this is the proper context for this question, but I found the closest related post <a href="https://github.com/BlueDragonX/xf86-input-mtrack/issues/14">here</a>.  Unfortunately, I am very new to automake.

I am having the exact same issue as described in the link above.  I tried running "autoreconf -i" as suggested, but it fails with this output:

Can't exec "libtoolize": No such file or directory at /usr/bin/autoreconf line 189.
Use of uninitialized value in pattern match (m//) at /usr/bin/autoreconf line 189.
configure.ac:23: error: xorg-macros version 1.8 or higher is required but 1.5.0 found
/usr/share/aclocal/xorg-macros.m4:39: XORG_MACROS_VERSION is expanded from...
configure.ac:23: the top level
autom4te: /usr/bin/m4 failed with exit status: 1
aclocal: /usr/bin/autom4te failed with exit status: 1
autoreconf: aclocal failed with exit status: 1

Does anyone have any advice on attacking this issue?  Do I have the right approach to building, or should I be doing something else?

Edit: Apologies for the misplaced post.  If anyone else has this issue, I found an updated file at ftp.x.org (http://ftp.x.org/pub/individual/util/).  I downloaded the most recent version of util-macros (util-macros-1.16.2.tar.gz in my case) and configured it using the instructions in the included INSTALL file.  I then manually copied the file to the appropriate location (/usr/share/aclocal/xorg-macros.m4 for me).  I later needed to install libtool (sudo apt-get install libtool) and add a soft link to /usr/share/aclocal/ (ln -s /usr/bin/libtool /usr/share/aclocal/LIBTOOL); it finally built with "autoreconf -i".

**Comment by duzy** [comment]
install `xutils-dev` for `xorg-macros`

**Comment by lukovdm** [comment]
It worked, thanks

**Comment by szdrnja** [comment]
I managed to get it to work by downloading the newest version of util-macros from http://ftp.x.org/pub/individual/util/ and then running:
./configure
sudo make install
sudo cp ./xorg-macros.m4 /usr/share/alocal
and then from the setxkbmap dir
autoreconf -i
automake
I've tried following the INSTALL guide under util-macros directory but none of it worked - maybe this end result was somehow influenced by that. 
from there run:
./configure
make 
and you should see the executable file in your dir

**Comment by oleg-alexandrov** [comment]
I ran into the same problem. But I could not copy the xorg-macros to the system directory since I don't have sudo access. What worked was to build and install that in my local directory, and then set

export ACLOCAL_PATH=/path/to/my/share/aclocal

before running autogen.sh or other build tools.

**Comment by yimuchuanye** [comment]
> I ran into the same problem. But I could not copy the xorg-macros to the system directory since I don't have sudo access. What worked was to build and install that in my local directory, and then set
> 
> export ACLOCAL_PATH=/path/to/my/share/aclocal
> 
> before running autogen.sh or other build tools.

THANKS! 
I set
       export ACLOCAL_PATH=$ACLOCAL_PATH:/path/to/my/share/aclocal
