### ISSUE TITLE
Support for Disabling the Trackpad While Typing

### ISSUE THREAD

**Issue by rynbrd** [BlueDragonX/xf86-input-mtrack#4]
The mtrack driver should support disabling the trackpad while typing.  This depends on properties support.

**Comment by miladrakhsha** [comment]
Hi,

I am trying to install dispad on my ubuntu 12.04 on 8,1 macbookpro. When I try to make && isntall it gives me this error. Everything before this step went smoothly without any error.

milad@milad-MacBookPro:~/Downloads/dispad-master$ make && make install
Making all in src
make[1]: Entering directory `/home/milad/Downloads/dispad-master/src'
gcc -DPACKAGE_NAME=\"dispad\" -DPACKAGE_TARNAME=\"dispad\" -DPACKAGE_VERSION=\"0.1\" -DPACKAGE_STRING=\"dispad\ 0.1\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_URL=\"\" -DPACKAGE=\"dispad\" -DVERSION=\"0.1\" -DHAVE_LIBXI=1 -DHAVE_LIBX11=1 -I. -I../include/    -g -O2 -MT conf.o -MD -MP -MF .deps/conf.Tpo -c -o conf.o conf.c
conf.c:30:21: fatal error: confuse.h: No such file or directory
compilation terminated.
make[1]: *** [conf.o] Error 1
make[1]: Leaving directory `/home/milad/Downloads/dispad-master/src'
make: *** [all-recursive] Error 1
milad@milad-MacBookPro:~/Downloads/dispad-master$ 

Can you help me with this?
Thank you in advance.

**Comment by BlueDragonX** [comment]
You need to install the libconfuse dev library.

**Comment by miladrakhsha** [comment]
Thank you for your response. I did what you said by doing sudo apt-get install libconfuse-dev,  but this time it gives me this error:

milad@milad-MacBookPro:~/Downloads/dispad-master$ make && make install
Making all in src
make[1]: Entering directory `/home/milad/Downloads/dispad-master/src'
gcc  -g -O2   -o dispad conf.o control.o dispad.o listen.o  -lX11 -lXi 
conf.o: In function `config_file_parse':
/home/milad/Downloads/dispad-master/src/conf.c:116: undefined reference to `cfg_init'
/home/milad/Downloads/dispad-master/src/conf.c:117: undefined reference to `cfg_parse'
/home/milad/Downloads/dispad-master/src/conf.c:118: undefined reference to `cfg_free'
collect2: ld returned 1 exit status
make[1]: *** [dispad] Error 1
make[1]: Leaving directory `/home/milad/Downloads/dispad-master/src'
make: *** [all-recursive] Error 1

**Comment by BlueDragonX** [comment]
What version of libconfuse-dev do you have installed?

**Comment by art321** [comment]
Hello. I have this error on Ubuntu 18.04 :

`user@X:~/Downloads/dispad$ sudo make
Making all in src
make[1]: Entering directory '/home/ben/Downloads/dispad/src'
gcc -DPACKAGE_NAME=\"dispad\" -DPACKAGE_TARNAME=\"dispad\" -DPACKAGE_VERSION=\"0.1\" -DPACKAGE_STRING=\"dispad\ 0.1\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_URL=\"\" -DPACKAGE=\"dispad\" -DVERSION=\"0.1\" -DHAVE_LIBX11=1 -DHAVE_LIBCONFUSE=1 -I.  -I../include/   -g -O2 -MT control.o -MD -MP -MF .deps/control.Tpo -c -o control.o control.c
In file included from control.c:22:0:
../include/control.h:27:10: fatal error: X11/extensions/XInput.h: No such file or directory
 #include <X11/extensions/XInput.h>
          ^~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
Makefile:341: recipe for target 'control.o' failed
make[1]: *** [control.o] Error 1
make[1]: Leaving directory '/home/ben/Downloads/dispad/src'
Makefile:331: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1


I already installed **libconfuse-dev** version **(3.2.1+dfsg-4)**.
Can you help me?
Thanks.



`
