### ISSUE TITLE
ThinkPad T440s: only upper 5% of the touchpad are outside "ButtonEdge"

### ISSUE THREAD

**Issue by ribx** [BlueDragonX/xf86-input-mtrack#71]
When using the mtrack driver, I have to start all movment and make all taps and gesture on the upper 5% of the touchpad. Note that exatcly at this position there is a read line on the touchpad.

I tried to disable the `ButtonEdge` by setting it to 0 without success. evtest shows me normal behaviour everywhere on the touchpad, even QuadTaps.

This is my `xinput watch-props` output with the synaptics driver (i cannot copy and paste the output with mtrack and somehow xinput does not send the output to a pipe or a file, no clue why):
```
Device 'TPPS/2 IBM TrackPoint':
	Device Enabled (134):	1
	Coordinate Transformation Matrix (136):	1.000000, 0.000000, 0.000000, 0.000000, 1.000000, 0.000000, 0.000000, 0.000000, 1.000000
	Device Accel Profile (259):	0
	Device Accel Constant Deceleration (260):	1.000000
	Device Accel Adaptive Deceleration (261):	1.000000
	Device Accel Velocity Scaling (262):	10.000000
	Device Product ID (253):	2, 10
	Device Node (254):	"/dev/input/event5"
	Evdev Axis Inversion (297):	0, 0
	Evdev Axes Swap (299):	0
	Axis Labels (300):	"Rel X" (144), "Rel Y" (145)
	Button Labels (301):	"Button Left" (137), "Button Middle" (138), "Button Right" (139), "Button Wheel Up" (140), "Button Wheel Down" (141)
	Evdev Middle Button Emulation (302):	0
	Evdev Middle Button Timeout (303):	50
	Evdev Third Button Emulation (304):	0
	Evdev Third Button Emulation Timeout (305):	1000
	Evdev Third Button Emulation Button (306):	3
	Evdev Third Button Emulation Threshold (307):	20
	Evdev Wheel Emulation (308):	0
	Evdev Wheel Emulation Axes (309):	0, 0, 4, 5
	Evdev Wheel Emulation Inertia (310):	10
	Evdev Wheel Emulation Timeout (311):	200
	Evdev Wheel Emulation Button (312):	4
	Evdev Drag Lock Buttons (313):	0
```

Please let me know how I can provide more information.

**Comment by BlueDragonX** [comment]
Frankly I don't know. It may require a kernel driver update in any case.

**Comment by p2rkw** [comment]
@ribx: bit late, but can you try this: https://github.com/p2rkw/xf86-input-mtrack/commit/6f03cc5d504ef1db4fbe88b1a4277d4899ec5e25 ?
