### ISSUE TITLE
Two Finger Tap not working Macbook Air Trackpad

### ISSUE THREAD

**Issue by mrgalup** [BlueDragonX/xf86-input-mtrack#76]
Hello,

First off, this is an amazing driver that has completely fixed the lack of functionality for the Macbook Air Trackpad in Ubuntu 14.04 for me. There are only a few outstanding issues that I cannot solve. Two finger tap to right click is highly intermittent, to the degree where I sometimes have to forcefully tap on the trackpad, and it still only works about 60% of the time. Below are my customized settings:

	Option		"IgnoreThumb"		"1"
	Option		"IgnorePalm"		"1"
	Option		"TapDragEnable"		"0"
	Option		"FingerHigh"		"12"
	Option		"FingerLow"		"1"
	Option 		"Sensitivity"		"0.85"
	Option		"ButtonMoveEmulate"	"0"
	Option		"ClickFinger1"		"0"
	Option		"ClickFinger2"		"0"
	Option		"ClickFinger3"		"0"
	Option		"ClickTime"		"50"
	Option		"MaxTapMove"		"200"
	Option		"ScrollDistance"	"75"

Thanks for your help in advance and I hope this post helps others in my position!

**Comment by BlueDragonX** [comment]
Many of the settings you have set there will have an adverse affect on the drivers ability to track multiple fibers for tapping. Remove FingerHigh, FingerLow,  and MaxTapMove and see if that improves things.

**Comment by mrgalup** [comment]
Ryan,

Thank you so much for your speedy response and for your advice. Removed
these settings seems to have solved the problem!

Once again, superb work on this driver. I scoured the internet to find a
solution to the macbook air trackpad being practically useless, as well as
modifying bunches of synclient options to no avial. Kudos on the fine work
and I will recommend it to anyone I know.


Best,
Mark

On Sat, Jan 10, 2015 at 10:54 AM, Ryan Bourgeois <notifications@github.com>
wrote:

> Many of the settings you have set there will have an adverse affect on the
> drivers ability to track multiple fibers for tapping. Remove FingerHigh,
> FingerLow, and MaxTapMove and see if that improves things.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/BlueDragonX/xf86-input-mtrack/issues/76#issuecomment-69462500>
> .
>



-- 
*Mark Galup**   |  *Producer/Engineer/Mixer, Multi-Instrumentalist
615.788.1969

*Recording, Mixing, & Mastering*
ReelRecording.com



*Like us on Facebook* <https://www.facebook.com/ReelRecording>
*Follow us on Twitter* <https://twitter.com/ReelRecording>

**Comment by BlueDragonX** [comment]
Thanks!

**Comment by mrgalup** [comment]
Hello Ryan,

I apologize if this is an inconvenience, but I wondered if you had any
insight on settings which might help avoid my palm triggering tap clicks
while typing. I do some competitive coding and when I'm really moving I
find that my palm often will do this. My settings are below:

Option "IgnoreThumb" "1"
Option "IgnorePalm" "1"
Option "TapDragEnable" "0"
Option "Sensitivity" "0.85"
Option "ButtonMoveEmulate" "0"
Option "ClickFinger1" "0"
Option "ClickFinger2" "0"
Option "ClickFinger3" "0"
Option "ClickTime" "50"
Option "ScrollDistance" "50"

Thank you in advance for your time!

On Sat, Jan 10, 2015 at 4:48 PM, Ryan Bourgeois <notifications@github.com>
wrote:

> Thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/BlueDragonX/xf86-input-mtrack/issues/76#issuecomment-69475403>
> .
>



-- 
*Mark Galup**   |  *Producer/Engineer/Mixer, Multi-Instrumentalist
615.788.1969

*Recording, Mixing, & Mastering*
ReelRecording.com



*Like us on Facebook* <https://www.facebook.com/ReelRecording>
*Follow us on Twitter* <https://twitter.com/ReelRecording>

**Comment by BlueDragonX** [comment]
Use dispad: https://github.com/BlueDragonX/dispad

It disables the trackpad while typing. Then you can set IgnoreThumb and IgnorePalm to 0.
