### ISSUE TITLE
Simultaneous X and Y scrolling

### ISSUE THREAD

**Issue by JP-Ellis** [BlueDragonX/xf86-input-mtrack#77]
Is it possible to configure the driver such that using two fingers to scroll can be simultaneously done in both X and Y?  So for example, moving two fingers diagonally results in a diagonal scroll.

Also, is it possible to change the horizontal and vertical scrolling speeds?

**Comment by BlueDragonX** [comment]
It is not possible to scroll in both directions simultaneously. Scrolling is implemented as a gesture which triggers button clicks. By default the buttons it triggers are those associated with a standard scroll wheel.

You can adjust scrolling sensitivity with ScrollDistance.
