### ISSUE TITLE
Links to Gentoo and Ubuntu binaries in readme seem to be hijacked

### ISSUE THREAD

**Issue by FSund** [BlueDragonX/xf86-input-mtrack#89]
The links
* [Gentoo](http://www.dev.fatalmachine.org/xf86-input-mtrack/gentoo) (http://www.dev.fatalmachine.org/xf86-input-mtrack/gentoo)

and
* [Ubuntu](http://www.dev.fatalmachine.org/xf86-input-mtrack/ubuntu) (http://www.dev.fatalmachine.org/xf86-input-mtrack/ubuntu)

in the readme brings me to a site that wants to sell me an iPhone for 1 cent.

**Comment by BlueDragonX** [comment]
Removed them.
